- poldek support the proper way (one more thing left to do - need poldek change)
Changed files:
    util-vserver-build-poldek.patch -> 1.7

diff --git a/util-vserver-build-poldek.patch b/util-vserver-build-poldek.patch
--- a/util-vserver-build-poldek.patch
+++ b/util-vserver-build-poldek.patch
@@ -200,6 +200,192 @@ diff -urN -x '*~' util-vserver-0.30.207/scripts/functions util-vserver-0.30.207-
  	    *)		echo "Unknown packaging flavor" >&2; exit 1;;
  	esac
      done
+@@ -741,6 +743,27 @@
+     test -n "$have_yum" && return 0 || return 1
+ }
+ 
++## Usage: pkgmgmt.isPoldekAvailable <cfgdir> <vdir> [<is-internal>]
++function pkgmgmt.isPoldekAvailable
++{
++    local cfgdir="$1"
++    local vdir="$2"
++    local is_internal="$3"
++    
++    local have_poldek i
++    if test -n "$is_internal"; then
++	have_poldek=1
++	test -d "$cfgdir"/base/poldek -o -d "$cfgdir"/poldeketc || have_poldek=
++    else
++	have_poldek=
++	for i in /bin /usr/bin /usr/local/bin; do
++	    test ! -x "$vdir$i"/poldek || { have_poldek=1; break; }
++	done
++    fi
++
++    test -n "$have_poldek" && return 0 || return 1
++}
++
+ 
+ function vshelper.doSanityCheck
+ {
+diff -ur -x '*~' -x .libs -x .deps util-vserver-0.30.207/scripts/pkgmgmt util-vserver-0.30.207-poldek/scripts/pkgmgmt
+--- util-vserver-0.30.207/scripts/pkgmgmt	2005-04-28 20:03:22.000000000 +0200
++++ util-vserver-0.30.207-poldek/scripts/pkgmgmt	2005-05-20 18:36:25.812617328 +0200
+@@ -174,7 +174,7 @@
+ "
+     
+     case $2 in
+-	(RH)	pkgs=$(vrpm "$1" -- -q --qf '---%{NAME}---\n' rpm apt yum "${YUM_RELEASEPKGS[@]}")
++	(RH)	pkgs=$(vrpm "$1" -- -q --qf '---%{NAME}---\n' rpm apt yum poldek "${YUM_RELEASEPKGS[@]}")
+ 		hasSubstring "$pkgs" ---rpm--- || {
+ 		    warning "$ERR
+ * The vserver does not seem to have the 'rpm' package which is required
+@@ -184,9 +184,9 @@
+ 		    ERR=
+ 		}
+ 		
+-		hasSubstring "$pkgs"  ---apt--- ---yum--- || {
++		hasSubstring "$pkgs"  ---apt--- ---yum--- ---poldek--- || {
+ 		    warning "$ERR
+-* The vserver does not seem to have a depsolver like 'apt' or 'yum'
++* The vserver does not seem to have a depsolver like 'apt', 'yum' or 'poldek'
+   installed. It is suggested to install such a program before setting
+   up internal package management."
+ 		    res=1
+@@ -341,6 +341,125 @@
+     fi
+ }
+ 
++function processVserver_PLD()
++{
++    local vserver=$1
++    local is_internalize=$2
++    local cfgdir
++    local i
++
++    cfgdir=$($_VSERVER_INFO "$vserver" APPDIR pkgmgmt) || \
++    cfgdir=$($_VSERVER_INFO "$vserver" APPDIR)/pkgmgmt
++
++    ## Figure out the environment....
++    pkgmgmt.isPoldekAvailable "$cfgdir" "$vdir" "$is_internalize" || have_poldek=
++
++    local POLDEKETCDIR=
++    local POLDEKCACHEDIR=
++    local RPMETCDIR=
++    local RPMSTATEDIR=
++
++    ## Create directories and assign variables where configuration
++    ## can/will be found on the host
++    if test -n "$is_internalize"; then
++	verifyInternalPackages "$vserver" RH || test -n "$IS_FORCE" ||
++	    panic "
++Can not continue; use '--force' to override this check"
++    
++	pushd "$vdir" >/dev/null
++
++	test ! -L var/lib/rpm || {
++	    $_EXEC_CD /var/lib $_RM            rpm &&
++	    $_EXEC_CD /var/lib $_MKDIR -m755   rpm &&
++	    $_EXEC_CD /var/lib $_CHOWN rpm:rpm rpm ||
++	    :
++	} </dev/null 2>/dev/null
++
++	for i in var/tmp/poldek-cache etc/rpm; do
++	    test -d "$i" ||
++		$_EXEC_CD /$(dirname "$i") $_MKDIR -m755 $(basename "$i") || :
++	done #2>/dev/null
++	
++	popd >/dev/null
++	
++	if test -n "$have_poldek"; then
++	    findDir POLDEKETCDIR    "$cfgdir"/poldeketc "$cfgdir"/base/poldek/etc /etc
++	fi
++
++	findDir RPMETCDIR   "$cfgdir"/rpmetc   "$cfgdir"/base/rpm/etc    /etc/rpm /
++	findDir RPMSTATEDIR "$cfgdir"/rpmstate "$cfgdir"/base/rpm/state
++    else
++	mkdir -m755 -p "$cfgdir"
++	local need_base=
++
++	if test -n "$have_poldek"; then
++	    findDir POLDEKETCDIR   "$cfgdir"/poldeketc    "$cfgdir"/base/poldek/etc    /etc /
++	    findDir POLDEKCACHEDIR "$cfgdir"/poldek-cache "$cfgdir"/base/poldek/cache       /
++	    
++	    test "$POLDEKETCDIR"    != / || POLDEKETCDIR=$cfgdir/base/poldek/etc
++	    test "$POLDEKCACHEDIR"  != / || POLDEKCACHEDIR=$cfgdir/base/poldek/cache
++
++	    test -d "$cfgdir"/poldeketc -a -d "$cfgdir"/poldek-cache || need_base=1
++	fi
++
++	findDir RPMETCDIR     "$cfgdir"/rpmetc   "$cfgdir"/base/rpm/etc    /
++	findDir RPMSTATEDIR   "$cfgdir"/rpmstate "$cfgdir"/base/rpm/state  /
++
++	test "$RPMETCDIR"   != / || RPMETCDIR=$cfgdir/base/rpm/etc
++	test "$RPMSTATEDIR" != / || RPMSTATEDIR=$cfgdir/base/rpm/state
++
++	test -d "$cfgdir"/rpmetc -a -d "$cfgdir"/rpmstate || need_base=1
++	test ! -e "$cfgdir"/base || need_base=
++
++	test -z "$need_base" || ln -s "$PKGCFGDIR" "$cfgdir"/base
++
++	mkdir -m755 -p "$PKGCFGDIR"
++	_createDirs "$POLDEKETCDIR" "$POLDEKCACHEDIR" \
++		    "$RPMETCDIR" "$RPMSTATEDIR"
++    fi
++
++    ## Copy the files...
++    if test -n "$is_internalize"; then
++	if test -n "$have_poldek"; then
++	    _copySecure "$vdir" "$POLDEKETCDIR" /etc/poldek
++	    pushd "$vdir" >/dev/null
++		_hashAuto /etc/poldek.conf '/'
++	    popd >/dev/null
++	fi
++
++	_copySecure "$vdir" "$RPMETCDIR"   /etc/rpm
++	_copySecure "$vdir" "$RPMSTATEDIR" /var/lib/rpm
++
++    else
++	if test -n "$have_poldek"; then
++	    _copySecureRev "$vdir" /etc/poldek "$POLDEKETCDIR"
++	    _unhashAuto "$POLDEKETCDIR"/poldek.conf '/'
++	fi
++
++	_copySecureRev "$vdir" /etc/rpm     "$RPMETCDIR"
++	_copySecureRev "$vdir" /var/lib/rpm "$RPMSTATEDIR"
++    fi
++
++    ## Cleanups...
++    if test -n "$is_internalize"; then
++	:
++    else
++	tmpdir=$($_MKTEMPDIR /var/tmp/pgmgmt.XXXXXX)
++	trap "$_RM -rf $tmpdir" EXIT
++	pushd "$vdir" >/dev/null
++	$_EXEC_CD /var/lib $_MV rpm $tmpdir/
++	$_EXEC_CD /var/lib $_LN_S "$rpmdb_mntpoint" rpm
++	$_RM -rf $tmpdir
++    fi
++
++    ## Finish it...
++    if test -n "$is_internalize"; then
++	$_TOUCH "$cfgdir"/internal
++    else
++	$_RM -f "$cfgdir"/internal
++    fi
++}
++
+ function processVserver_Debian()
+ {
+     local vserver=$1
+@@ -390,6 +509,7 @@
+ 
+     case "$style" in
+ 	(redhat|mandrake)	processVserver_RH     "$vserver" "$IS_INTERNALIZE";;
++	(pld)			processVserver_PLD    "$vserver" "$IS_INTERNALIZE";;
+ 	(debian)		processVserver_Debian "$vserver" "$IS_INTERNALIZE";;
+ 	(*)
+ 	    echo $"Vserver style '$style' is not supported for packagemanagment" >&2
 diff -urN -x '*~' util-vserver-0.30.207/scripts/util-vserver-vars.pathsubst util-vserver-0.30.207-poldek/scripts/util-vserver-vars.pathsubst
 --- util-vserver-0.30.207/scripts/util-vserver-vars.pathsubst	2005-03-23 03:05:39.000000000 +0100
 +++ util-vserver-0.30.207-poldek/scripts/util-vserver-vars.pathsubst	2005-05-17 15:47:26.102795896 +0200
@@ -356,7 +542,7 @@ diff -urN -x '*~' util-vserver-0.30.207/scripts/vpoldek-worker util-vserver-0.30
 +vserver="$1"
 +shift
 +
-+pkgInit "$vserver" poldek
++pkgInit "$vserver" rpm poldek
 +
 +test -z "$_POLDEK" || {
 +    warning $"The environment variable \$_POLDEK is not supported anymore; please use \$POLDEK instead of"
@@ -464,7 +650,7 @@ diff -urN -x '*~' util-vserver-0.30.207/scripts/vserver-build.functions.poldek u
 diff -urN -x '*~' util-vserver-0.30.207/scripts/vserver-build.poldek util-vserver-0.30.207-poldek/scripts/vserver-build.poldek
 --- util-vserver-0.30.207/scripts/vserver-build.poldek	1970-01-01 01:00:00.000000000 +0100
 +++ util-vserver-0.30.207-poldek/scripts/vserver-build.poldek	2005-05-17 15:47:26.106795288 +0200
-@@ -0,0 +1,53 @@
+@@ -0,0 +1,61 @@
 +# $Id$	--*- sh -*--
 +
 +# Copyright (C) 2003 Enrico Scholz <enrico.scholz@informatik.tu-chemnitz.de>
@@ -485,6 +671,7 @@ diff -urN -x '*~' util-vserver-0.30.207/scripts/vserver-build.poldek util-vserve
 +tmp=$(getopt -o +d: --long debug -n "$0" -- "$@") || exit 1
 +eval set -- "$tmp"
 +
++. "$_LIB_VSERVER_BUILD_FUNCTIONS_RPM"
 +. "$_LIB_VSERVER_BUILD_FUNCTIONS_POLDEK"
 +. "$_LIB_VSERVER_BUILD_FUNCTIONS_PKGMGMT"
 +
@@ -504,16 +691,23 @@ diff -urN -x '*~' util-vserver-0.30.207/scripts/vserver-build.poldek util-vserve
 +
 +base.initVariables
 +pkgmgmt.initVariables
++rpm.initVariables
 +poldek.initVariables
 +
 +base.initFilesystem    "$OPTION_FORCE"
 +pkgmgmt.initFilesystem "$OPTION_FORCE"
++rpm.initFilesystem
 +poldek.initFilesystem
 +
 +setup_writeOption "$VSERVER_NAME"
 +setup_writeInitialFstab
 +
 +test -z "$BUILD_INITPRE"  || "$BUILD_INITPRE" "$SETUP_CONFDIR"  "$UTIL_VSERVER_VARS"
++rpm.initDB	      "$SETUP_CONFDIR"
++rpm.importGPGPubKeys "$SETUP_CONFDIR" \
++	"$__CONFDIR/.distributions/$DISTRIBUTION/pubkeys" \
++	"$__CONFDIR/.distributions/.common/pubkeys" \
++	"$__DISTRIBDIR/$DISTRIBUTION/pubkeys"
 +
 +$_VPOLDEK "$SETUP_CONFDIR" -- --update-whole
 +poldek.installBasePackages "$SETUP_CONFDIR" "$PKGINSTALLDIR"
