- tabs
Changed files:
    vprocunhide.init -> 1.4

diff --git a/vprocunhide.init b/vprocunhide.init
--- a/vprocunhide.init
+++ b/vprocunhide.init
@@ -10,50 +10,50 @@
 
 [ -n "$UTIL_VSERVER_VARS" ] || UTIL_VSERVER_VARS=/usr/lib/util-vserver/util-vserver-vars
 if [ ! -e "$UTIL_VSERVER_VARS" ] ; then
-    echo "Can not find util-vserver installation (the file '$UTIL_VSERVER_VARS' would be expected); aborting..." >&2
-    exit 1
+	echo "Can not find util-vserver installation (the file '$UTIL_VSERVER_VARS' would be expected); aborting..." >&2
+	exit 1
 fi
 . "$UTIL_VSERVER_VARS"
 
 case "$1" in
-    start)
+start)
 	if [ ! -d /proc/virtual ]; then
-	    show "Fixing vservers /proc entries visibility. kernel not capable"
-	    fail
-	    exit 1
+		show "Fixing vservers /proc entries visibility. kernel not capable"
+		fail
+		exit 1
 	fi
 
-    	show "Fixing vservers /proc entries visibility"
+	show "Fixing vservers /proc entries visibility"
 	busy
 	$_VPROCUNHIDE
 	RETVAL=$?
 	deltext
 	case "$RETVAL" in
-	    0)	ok;;
-	    2)	ok; RETVAL=0;;
-	    *)	fail;;
+		0)	ok;;
+		2)	ok; RETVAL=0;;
+		*)	fail;;
 	esac
 	[ "$RETVAL" -eq 0 ] && touch /var/lock/subsys/vprocunhide
 	;;
-    stop)
-    	show "Stopping vservers /proc entries visibility"
+stop)
+	show "Stopping vservers /proc entries visibility"
 	busy
 	rm -f /var/lock/subsys/vprocunhide
 	ok
 	;;
-    restart|reload)
-    	$0 stop
+restart|reload)
+	$0 stop
 	$0 start
 	;;
-    status)
-    	if [ -f /var/lock/subsys/vprocunhide ] ; then
-	    echo "vservers /proc entries were fixed"
+status)
+	if [ -f /var/lock/subsys/vprocunhide ] ; then
+		echo "vservers /proc entries were fixed"
 	else
-	    echo "vservers /proc entries are not fixed"
+		echo "vservers /proc entries were not fixed"
 	fi
 	;;
-    *)
-        echo "Usage: $0 {start|stop|reload|restart|status}"
+*)
+	echo "Usage: $0 {start|stop|reload|restart|status}"
 	exit 1
 	;;
 esac
@@ -61,4 +61,4 @@ esac
 exit $RETVAL
 
 # This must be last line !
-# vi:syntax=sh:tw=78:ts=8:sw=4
+# vi:syntax=sh:tw=78:ts=4:sw=4
